learning_templates/basic_app/urls.py
# from django.conf.urls import url
# from basic_app import views
#
# #for template tagging, set a variable name-global name and app name
# app_name = 'basic_app'
#
#
# urlpatterns = [
#     url(r'^relative/$', views.relative, name = 'relative'),
#
#     url(r'^other/$', views.other, name = 'other'),
#
# ]

from django.urls import path
from . import views

# SET THE NAMESPACE!
app_name = 'basic_app'

urlpatterns=[
    path('relative/',views.relative,name='relative'),
    path('other/',views.other,name='other'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from basic_app import views

urlpatterns = [
    
    url(r'^$', views.index, name = 'index'),
    path('admin/', admin.site.urls),
    url(r'^basic_app/', include('basic_app.urls')),
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context_dict ={'text': 'hello world', 'number': 100}
    return render(request, 'basic_app/index.html',context_dict)


def other(request):
    return render(request, 'basic_app/other.html')


def relative(request):
    return render(request,'basic_app/relative_url_templates.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-nav">
        <a class="navbar-brand" href="{% url 'index' %}">BRAND</a>
        <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
        <a class="nav-item nav-link" href="{% url 'basic_app:other' %}">Other</a>
        <a class="nav-item nav-link" href="{% url 'basic_app:relative' %}">Relative</a>
      </div>
    </nav>

    <div class="container">
    {% block body_block %}
    {# Anything outside of this will be inherited if you use extend.#}
    {% endblock %}
    </div>

  </body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>

{% extends "basic_app/base.html" %}
  {% block body_block %}

    <h1>Welcome to Index </h1>
    <h1>This is index.html page showing</h1>

    <!-- using built-in function -->
    <!-- <h1> {{ text|upper }}</h1> -->
    <h1> {{ number|add:'99' }}  </h1>

    <!-- using customized filter -->
    <h1>{{ text|cut:'world' }}</h1>
 s
    {% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}

    <h1>Welcome to Other.html</h1>

  {% endblock %}
</html>

learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% block body_block %}
    <h1>welcome to relative_url_templates</h1>
    <p>Here are the useful links</p>

    <a href="{% url 'basic_app:other' %}">Link to other.html</a>
    <!-- basic_app is an app name in urls.py of basic_app folder, which is app_name = 'basic_app' -->
    <!-- and 'other' came from url(r'^other/$', views.other, name = 'other'), from urls.py of basic_app -->
    <a href="{% url 'admin:index' %}">Link to Admin Page</a>

    <a href="{% url 'basic_app:relative' %}">Link to relative.html</a>
    {% endblock %}

  </body>
</html>